{"uuid": "af3c21a5-1dc9-4804-aaa5-456072e3a27f", "children": ["71b2ded4-e3c8-4ce0-8f4d-fb620cb26c2c"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1696848852174, "stop": 1696848852174}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00B2A813+48355]\n\t(No symbol) [0x00ABC4B1]\n\t(No symbol) [0x009C5358]\n\t(No symbol) [0x009AD293]\n\t(No symbol) [0x00A0E37B]\n\t(No symbol) [0x00A1C473]\n\t(No symbol) [0x00A0A536]\n\t(No symbol) [0x009E82DC]\n\t(No symbol) [0x009E93DD]\n\tGetHandleVerifier [0x00D8AABD+2539405]\n\tGetHandleVerifier [0x00DCA78F+2800735]\n\tGetHandleVerifier [0x00DC456C+2775612]\n\tGetHandleVerifier [0x00BB51E0+616112]\n\t(No symbol) [0x00AC5F8C]\n\t(No symbol) [0x00AC2328]\n\t(No symbol) [0x00AC240B]\n\t(No symbol) [0x00AB4FF7]\n\tBaseThreadInitThunk [0x75747BA9+25]\n\tRtlInitializeExceptionChain [0x77B0BC5B+107]\n\tRtlClearBits [0x77B0BBDF+191]\n\n", "trace": "  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\TestCases\\conftest.py\", line 31, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"miao\", attachment_type=AttachmentType.PNG)\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\fardi\\PycharmProjects\\Rokomari_WebAutomation_Project\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1696848882259, "stop": 1696848882261}], "start": 1696848852174, "stop": 1696848882261}