{"name": "test_SignUp_with_invalid_mail[chrome]", "status": "passed", "attachments": [{"name": "log", "source": "c22e0639-db69-41ae-a8c5-a78f4a62c9c1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_browser", "value": "'chrome'"}], "start": 1696849137513, "stop": 1696849168593, "uuid": "aa79ac4e-52c2-4f8e-b87f-33b6df678cc8", "historyId": "001e20a29568cee169d0fd268377227a", "testCaseId": "ed3912fcb4c6811f198697c9f53e687d", "fullName": "test_SSO.Test_SSO#test_SignUp_with_invalid_mail", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure', 'get_browser')"}, {"name": "suite", "value": "test_SSO"}, {"name": "subSuite", "value": "Test_SSO"}, {"name": "host", "value": "CYREX-x-CYREX"}, {"name": "thread", "value": "10232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_SSO"}]}